// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHRkhJrixNNG81IK4drxJ2hM7OCZqCpwE',
    appId: '1:1086876264698:web:6c0ca87ddb2629e8cd4143',
    messagingSenderId: '1086876264698',
    projectId: 'geez-dbced',
    authDomain: 'geez-dbced.firebaseapp.com',
    storageBucket: 'geez-dbced.appspot.com',
    measurementId: 'G-E2NVL2QHPM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLyRruzS8jO4a6uNm8Ww35d_MPSJCxG4',
    appId: '1:1086876264698:android:f78e2ce10b5dff52cd4143',
    messagingSenderId: '1086876264698',
    projectId: 'geez-dbced',
    storageBucket: 'geez-dbced.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNoR1XrEgvoeGsfsp3Sy02ye5aZyBnUZs',
    appId: '1:1086876264698:ios:f5da6e0521d31270cd4143',
    messagingSenderId: '1086876264698',
    projectId: 'geez-dbced',
    storageBucket: 'geez-dbced.appspot.com',
    iosBundleId: 'com.example.geez',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNoR1XrEgvoeGsfsp3Sy02ye5aZyBnUZs',
    appId: '1:1086876264698:ios:747e3eff46b09f09cd4143',
    messagingSenderId: '1086876264698',
    projectId: 'geez-dbced',
    storageBucket: 'geez-dbced.appspot.com',
    iosBundleId: 'com.example.geez.RunnerTests',
  );
}
